"""
Triangular, pentagonal, hexagonal
Project Euler Problem #44
by Muaz Siddiqui

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from euler_helpers import is_pentagonal, is_hexagonal, timeit

@timeit
def answer():
    first = 286
    smallest = 0
    while not smallest:
        next = first*(first+1)/2
        if is_hexagonal(next) and is_pentagonal(next):
            smallest = next
        first += 1
    return smallest


